import sys
while True:
     while True:
         print(" .-----------------. .----------------.  .----------------.  ")
         print(" | .--------------. || .--------------. || .--------------. |") 
         print(" | | ____  _____  | || |   ______     | || |      __      | |")
         print(" | ||_   \|_   _| | || |  |_   _ \    | || |     /  \     | |")
         print(" | |  |   \ | |   | || |    | |_) |   | || |    / /\ \    | |")
         print(" | |  | |\ \| |   | || |    |  __'.   | || |   / ____ \   | |")
         print(" | | _| |_\   |_  | || |   _| |__) |  | || | _/ /    \ \_ | |")
         print(" | ||_____|\____| | || |  |_______/   | || ||____|  |____|| |")
         print(" | |              | || |              | || |              | |")
         print(" | '--------------' || '--------------' || '--------------' |")
         print(" '----------------'  '----------------'  '----------------' ")
         print("¡Bienvenido al generador de boxscores NBA!")
         print("En primer lugar, escribe 1 si quieres empezar y 2 si quieres salir")
         eleccion=input()
         if eleccion == "1":
             print("¡Genial! En primer lugar escribe los tiros de campo encestados")
             tiros_campo_encestados=input()
             print("Okey, ahora escribe los tiros de campo errados")
             tiros_campo_errados=input()
             def tiros_campo_porcentaje(tiros_campo_encestados,tiros_campo_errados):
                 cantidad_tiros_campo=int(tiros_campo_encestados)+int(tiros_campo_errados)
                 ratio_tiros_campo=int(tiros_campo_encestados)/int(cantidad_tiros_campo)
                 return ratio_tiros_campo*100
             print("Listo, ahora pasemos a los triples. Escribe los triples encestados")
             triples_encestados=input()
             print("Okey, ahora escribe los triples errados")
             triples_errados=input()
             def triples_porcentaje(triples_encestados,triples_errados):
                 cantidad_triples=int(triples_encestados) + int(triples_errados)
                 ratio_triples=int(triples_encestados)/int(cantidad_triples)
                 return ratio_triples*100
             print("Finalmente, vamos a los tiros libres. Escribe los tiros libres encestados")
             libres_encestados=input()
             print("Bien, ahora escribe los tiros libres errados")
             libres_errados=input()
             def libres_porcentaje(libres_encestados,libres_errados):
                 cantidad_libres=int(libres_encestados)+int(libres_errados)
                 ratio_libres=int(libres_encestados)/int(cantidad_libres)
                 return ratio_libres*100
             print("¡Listo! Ya tenemos la boxscore")
             print(" .----------------.   .----------------.   .----------------. ")
             print(" | .--------------. | | .--------------. | | .--------------. |")
             print(" | |              | | | |              | | | |              | |")
             print(" | | Porcentaje   | | | |  Porcentaje  | | | |   Porcentaje | |")
             print(" | | tiros        | | | |  triples     | | | |   tiros      | |")
             print(" | | de           | | | |              | | | |   libres     | |")
             print(" | | campo        | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | '--------------' | | '--------------' | | '--------------' |")
             print(" '----------------'   '----------------'   '----------------' ")
             print(" .----------------.   .----------------.   .----------------. ")
             print(" | .--------------. | | .--------------. | | .--------------. |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |      "+str(tiros_campo_porcentaje(tiros_campo_encestados,tiros_campo_errados)) +"    | | | |"+         str(triples_porcentaje(triples_errados,triples_errados))+"          | | | |"+    str(libres_porcentaje(libres_encestados,libres_errados))+"          | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | |              | | | |              | | | |              | |")
             print(" | '--------------' | | '--------------' | | '--------------' |")
             print(" '----------------'   '----------------'   '----------------'")
         if eleccion == "2":
             print("Okey, adiós :(")
             sys.exit()
